spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-account.xml
    database-change-log-table: dbchangelog_account
    database-change-log-lock-table: dbchangeloglock_account
  rabbitmq:
    host: localhost
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

mybatis:
  type-aliases-package: com.example.common.model.Account

server:
  port: 8081
logging:
  file:
    name: /var/log/spring.log