FROM openjdk:17-jdk-slim AS build
WORKDIR /build
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew clean build

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /build/transaction/build/libs/transaction-*.jar ./transaction.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "transaction.jar"]
