FROM openjdk:17-jdk-slim AS build
WORKDIR /build
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew clean build

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /build/common/build/libs/common-*.jar ./common.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "common.jar"]
