FROM openjdk:17-jdk-slim AS build
WORKDIR /build
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew clean build

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /build/account/build/libs/account-*.jar ./account.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "account.jar"]
