version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  common:
    build:
      context: .
      dockerfile: Dockerfile-common
    depends_on:
      - postgres
      - rabbitmq

  transaction:
    build:
      context: .
      dockerfile: Dockerfile-transaction
    depends_on:
      - common

  balance:
    build:
      context: .
      dockerfile: Dockerfile-balance
    depends_on:
      - common

  account:
    build:
      context: .
      dockerfile: Dockerfile-account
    depends_on:
      - common
