FROM openjdk:17-jdk-slim AS build
WORKDIR /build
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew clean build

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /build/balance/build/libs/balance-*.jar ./balance.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "balance.jar"]
