version: '3.8'
services:
  postgres:
    image: postgres:13 # Specific version instead of 'latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432" # Map to the correct internal Postgres port

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

#  app:
#    build: .
#    depends_on:
#      - postgres
#      - rabbitmq
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/yourdatabase
#      SPRING_DATASOURCE_USERNAME: youruser
#      SPRING_DATASOURCE_PASSWORD: yourpassword
#      SPRING_RABBITMQ_HOST: rabbitmq
#    ports:
#      - "8080:8080"
