spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  rabbitmq:
    host: localhost
    port: 5672

mybatis:
  type-aliases-package: com.example.account.model
