spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-common.xml
    database-change-log-table: dbchangelog_common
    database-change-log-lock-table: dbchangeloglock_common
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: rabbitmq
    port: 5672
server:
  port: 8080
