spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-balance.xml
    database-change-log-table: dbchangelog_balance
    database-change-log-lock-table: dbchangeloglock_balance

mybatis:
  type-aliases-package: com.example.common.model.Balance

server:
  port: 8082