spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-transaction.xml
    database-change-log-table: dbchangelog_transaction
    database-change-log-lock-table: dbchangeloglock_transaction
  rabbitmq:
    host: localhost
    port: 5672

mybatis:
  type-aliases-package: com.example.common.model.Transaction

server:
  port: 8083